# Generated by Django 4.2.3 on 2023-07-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='autor',
            new_name='author',
        ),
    ]
